mass: 0.25
inertia: {Ixx: 0.000601, Ixy: 0.0, Ixz: 0.0, Iyx: 0.0, Iyy: 0.000589, Iyz: 0.0, Izx: 0.0, Izy: 0.0, Izz: 0.01076}
arm_length: 0.1075 

max_angle: 80 #degree

num_props: 4
max_rpm: 16400
min_rpm: 5500
motor_coefficients: 4.0172e-07

mesh_path: "package://rotor_tm/mesh/snapdragonflight.stl"
