# Define the type of the connection
mechanism_type: "Rigid Link" 

# Define the total number of robots
num_of_robots: 3

# Define where the cable is attached at
rho: 
  - {x: -0.0940, y: -0.267, z: 0.0097}
  - {x: 0.3683, y: 0.0,    z: 0.0097}
  - {x: -0.0940, y: 0.267,  z: 0.0097}

# Define the initial yaw of each UAV
yaw_list: [0.0,0.0,0.0]
